[project]
version = "1.0.2"
source-url = "https://github.com/buildpacks/pack"

[[build.env]]
name = "BP_GO_TARGETS"
value = "./cmd/pack"

[[build.env]]
name = "BP_GO_BUILD_LDFLAGS"
value = "-s -w -X 'github.com/buildpacks/pack.Version=0.0.0'"
